# Generated by Django 5.2 on 2025-04-21 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutricode', '0004_meallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MealLog',
        ),
    ]
