# Generated by Django 5.2 on 2025-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutricode', '0007_customgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgoal',
            name='goal_name',
        ),
        migrations.RemoveField(
            model_name='customgoal',
            name='goal_value',
        ),
        migrations.AddField(
            model_name='customgoal',
            name='calories_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='customgoal',
            name='carbs_goal',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='customgoal',
            name='fat_goal',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='customgoal',
            name='protein_goal',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='customgoal',
            name='water_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='customgoal',
            name='goal_type',
            field=models.CharField(choices=[('Muscle Gain', 'Muscle Gain'), ('Weight Loss', 'Weight Loss'), ('Bulk', 'Bulk'), ('Keto', 'Keto'), ('Balanced', 'Balanced'), ('Plant based', 'Plant based'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
